eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#Mail properties
smtp:
  host: 3.64.181.237
  port: 25
  user: support@fiverity.com
  password: 

admin:
  name: FiVerity Support
  email:
    from:
      address: support@fiverity.com

#JWT Token Properties
webtoken:
  timeout:
    in:
      minutes: 1200
jwt:
  secretKey: ${JWT_SECRETKEY:NtrFkF8w8yktLH9Es9DG9Z/p9NyMmR/vQ4hgajsJL4X=}
      
#AWS SES secretsmanager
aws:
  ses:
    secretsmanager:
      accessKey: ${SM_ACCESSKEY:XXXX}
      secretKey: ${SM_SECRETKEY:XXXX}
      secretName: ${SM_SECRETNAME:XXXX}
      region: ${SM_REGION:XXXX}
